### ISSUE TITLE
Train some non-imagenet models

### ISSUE THREAD

**Issue by zachmayer** [datarobot/pic2vec#7]
It'd be a good idea to get some image datasets that are acceptible for commercial use and train some models on them.

E.g. satellite images, medical images, etc.

**Comment by joristaglio** [comment]
I believe these models will be proprietary– unless I'm wrong and we're going to train some custom open-source models, I'll close this until further notice

**Comment by zachmayer** [comment]
Correct.  Please convert this to a JIRA ticket
